# Generated by Django 4.2.7 on 2023-11-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='note',
            field=models.IntegerField(default=None),
        ),
    ]
