# Generated by Django 4.2.7 on 2023-11-30 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0002_post_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='note',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
