# Generated by Django 4.2.7 on 2023-12-01 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0005_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
